[package]
name = "ctoPdf"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-multipart = "0.4"
tokio = { version = "1", features = ["full"] }
headless_chrome = "1.0"
anyhow = "1.0"
futures-util = "0.3"
quick-xml = "0.22"
